#!/usr/bin/env php
<?php
namespace think;

// 命令行入口文件
// 加载基础文件
require __DIR__ . '/vendor/autoload.php';

// 应用初始化
$con = (new App())->console;

define('APP_ENV', \think\facade\Env::get("APP_ENV","test")); //应用环境 prod(生产),test(测试)

$con->run();